logging:
  level:
    org.springframework.data.couchbase.repository.query: DEBUG
server:
  port: 8080
#spring:
#  couchbase:
#    bootstrap-hosts: "127.0.0.1"
#    bucket:
#      name: admin
#      password: admin123
#  data:
#    couchbase:
#      auto-index: true
